[package]
name = "mpvc"
version = "1.4.1"
authors = ["neeshy <neeshy@tfwno.gf>", "Jonas Frei <freijon@pm.me>"]
description = "An mpc-like CLI tool for mpv"
edition = "2021"

[dependencies]
clap = "4.3.24"
colored = "2.0.4"
log = "0.4.20"
serde = "=1.0.171"
serde_json = "1.0.105"

[dev-dependencies]
env_logger = "0.10.0"
notify = "6.1.1"
