[package]
name = "mpvc"
version = "1.2.6"
authors = [ "neeshy <neeshy@tfwno.gf>", "Jonas Frei <freijon@pm.me>" ]
description = "An mpc-like cli tool for mpv"

[dependencies]
clap = "4.3.19"
colored = "2.0.4"
log = "0.4.19"
serde = "1.0.181"
serde_json = "1.0.104"

[dev-dependencies]
env_logger = "0.10.0"
notify = "6.0.1"
