[package]
name = "mpvc"
version = "1.4.7"
authors = ["neeshy <neeshy@tfwno.gf>", "Jonas Frei <freijon@pm.me>"]
description = "An mpc-like CLI tool for mpv"
homepage = "https://github.com/neeshy/mpvc"
repository = "https://github.com/neeshy/mpvc.git"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
clap = "4.5.13"
clap_complete = "4.5.12"
colored = "2.1.0"
log = "0.4.22"
serde = "1.0.204"
serde_json = "1.0.121"

[dev-dependencies]
env_logger = "0.11.5"
notify = "6.1.1"
