[package]
name = "mpvc"
version = "1.1.4"
authors = [ "neeshy <neeshy@tfwno.gf>", "Jonas Frei <freijon@pm.me>" ]
description = "An mpc-like cli tool for mpv"

[dependencies]
clap = "4.1.13"
colored = "2.0.0"
log = "0.4.17"
serde = "1.0.158"
serde_json = "1.0.94"

[dev-dependencies]
env_logger = "0.10.0"
