[package]

name = "mpvc"
version = "1.1.1"
authors = [ "Jonas Frei <freijon@pm.me>" ]
description = "An mpc-like cli tool for mpv which connects to existing mpv instances through sockets."

[dependencies]
serde = "1.0.138"
serde_json = "1.0.82"
clap = "3.2.8"
colored = "2.0.0"
mpvipc = "=1.1.9"
#mpvipc = { path = "/home/jonas/Documents/Projects/mpvipc" }

