[package]

name = "mpvc"
version = "1.0.4"
authors = [ "Jonas Frei <freijon@gmail.com>" ]
description = "An mpc-like cli tool for mpv which connects to existing mpv instances through sockets."

[dependencies]
serde = "1.0.1"
serde_json = "1.0.0"
clap = "2.23.3"
colored = "1.5.0"
mpvipc = "=1.1.4"
#mpvipc = { path = "/home/jonas/Documents/Projects/mpvipc" }

