[package]

name = "mpvc"
version = "1.1.3"
authors = [ "Jonas Frei <freijon@pm.me>" ]
description = "An mpc-like cli tool for mpv which connects to existing mpv instances through sockets."

[dependencies]
serde = "1.0.140"
serde_json = "1.0.82"
clap = "3.2.14"
colored = "2.0.0"
mpvipc = "1.2.2"
#mpvipc = { path = "/home/jonas/Documents/Projects/mpvipc" }

